modLoader = "javafml"
loaderVersion = "*"
license = "LGPLv3"
issueTrackerURL = "https://github.com/Long-Zixuan/LSDC/issues"

[[mods]]
displayTest = "IGNORE_SERVER_VERSION"
modId = "embeddium_device_check"
version = "${version}"
displayName = "Embeddium Device Check"
logoFile = "icon.png"
updateJSONURL = ""
authors = "LoongLy"
displayURL = "https://modrinth.com/mod/sodium-device-check"
description = "Embeddium Device Check is Sodium Device Check with Forge support"

[[dependencies.embeddium_device_check]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.embeddium_device_check]]
modId = "embeddium"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.embeddium_device_check]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "CLIENT"
