modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPLv3"
issueTrackerURL="https://github.com/Long-Zixuan/LSDC/issues"

[[mods]]
modId = "lsdc"
version = "${version}"
displayName = "Rubidium Device Check"
logoFile= "icon.png"
authors = "LoongLy"
displayURL = "https://modrinth.com/mod/sodium-device-check"
description = "Rubidium Device Check is Sodium Device Check with forge support."

[[dependencies.lsdc]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lsdc]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.lsdc]]
modId = "caffeineconfig"
mandatory = true
versionRange = "[1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lsdc]]
modId = "rubidium"
mandatory = true
versionRange = "[0.5,)"
ordering = "NONE"
side = "BOTH"