modLoader = "javafml"
loaderVersion = "*"
license = "LGPLv3"
issueTrackerURL = ""

[[mods]]
displayTest = "IGNORE_SERVER_VERSION"
modId = "embeddium_extra"
version = "${version}"
displayName = "Embeddium Device Check"
logoFile = "icon.png"
updateJSONURL = ""
authors = "LoongLy"
displayURL = "https://modrinth.com/mod/sodium-device-check"
description = "Embeddium Device Check is Sodium Device Check with Forge support"

[[mixins]]
config = "lsdc.mixins.json"

[[dependencies.embeddium_extra]]
modId = "neoforge"
type = "required"
versionRange = "[20.6.119,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.embeddium_extra]]
modId = "embeddium"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.embeddium_extra]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "CLIENT"
