modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "lsdc"

version = "${version}"
displayName = "Sodium Chinese Localized Package"

logoFile = "icon.png" #optional

authors = "LoongLy"

description = '''
钠（Sodium）模组汉化包
'''

[[dependencies.lsdc]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.lsdc]]
modId = "sodium"
type = "required"
versionRange = "[0.8.1,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "lsdc.mixins.json"

[modproperties.lsdc]
"sodium:config_api_user" = "me.loongly.mods.lsdc.common.client.options.lsdcConfigBuilder"