modLoader = "javafml" #mandatory
loaderVersion = "${neoforge_loader_version_range}" #mandatory
license = "${license}" # Review your options at https://choosealicense.com/.
issueTrackerURL = "${issue_tracker_url}" #optional

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
displayURL = "${modrinth_url}" #optional (displayed in the mod UI)
logoFile = "assets/${mod_id}/icon.png" #optional
authors = "${mod_author}" #optional
description = '''${description}''' #mandatory (Supports multiline text)

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.forgeneoforge.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]]
modId = "sodium"
type = "required" #mandatory (Can be one of "required", "optional", "incompatible" or "discouraged")
versionRange = "[0.6.0-alpha.3,)"
ordering = "NONE"
side = "CLIENT"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
